### ISSUE TITLE
Floating point exception with cuda jit

### ISSUE THREAD

**Issue by WolframRhodium** [openppl-public/ppl.kernel.cuda#56]
https://github.com/openppl-public/ppl.kernel.cuda/blob/dfe7cb0c624747fc40ce1900a373200277caf94c/src/nn/conv/conv_jit.cc#L619

When `cta_num_per_launch` is 0, a floating point exception is raised here.

In my case, this happens because `cta_num_limit_by_smem` is 0:
https://github.com/openppl-public/ppl.kernel.cuda/blob/dfe7cb0c624747fc40ce1900a373200277caf94c/src/nn/conv/conv_jit.cc#L602-L605

Which in turn is because a previous check (line 1280) does not prevent this error:
https://github.com/openppl-public/ppl.kernel.cuda/blob/dfe7cb0c624747fc40ce1900a373200277caf94c/src/nn/conv/conv_fp16.cu#L1280-L1288

Since `max_dyn_smem_per_cta` is larger than `max_smem_per_sm`, the check using the former allows some invalid inputs to be consumed by the function.

**Comment by litianjian** [comment]
Can you provide the software and hardware environment in your case?

**Comment by WolframRhodium** [comment]
Ubuntu 22.04, CUDA 12.2.2, RTX 4090.

[RealESRGANv2-animevideo-xsx2.zip](https://github.com/openppl-public/ppl.kernel.cuda/files/14156194/RealESRGANv2-animevideo-xsx2.zip)
`tools/pplnn --in-shapes 1_3_128_128 --use-cuda --onnx-model RealESRGANv2-animevideo-xsx2.onnx`

**Comment by WolframRhodium** [comment]
There's also another issue here:
https://github.com/openppl-public/ppl.kernel.cuda/blob/dfe7cb0c624747fc40ce1900a373200277caf94c/src/nn/conv/conv_jit.cc#L131

With sm86 and sm89, the size is reduced.

**Comment by litianjian** [comment]
> Ubuntu 22.04, CUDA 12.2.2, RTX 4090.
> 
> [RealESRGANv2-animevideo-xsx2.zip](https://github.com/openppl-public/ppl.kernel.cuda/files/14156194/RealESRGANv2-animevideo-xsx2.zip) `tools/pplnn --in-shapes 1_3_128_128 --use-cuda --onnx-model RealESRGANv2-animevideo-xsx2.onnx`

Open-Sourced PPL only supports sm75 and sm80 now.

**Comment by litianjian** [comment]
> There's also another issue here:
> 
> https://github.com/openppl-public/ppl.kernel.cuda/blob/dfe7cb0c624747fc40ce1900a373200277caf94c/src/nn/conv/conv_jit.cc#L131
> 
> With sm86 and sm89, the size is reduced.

We will provide some improvements to cover the sm86 and sm89.

**Comment by WolframRhodium** [comment]
> Open-Sourced PPL only supports sm75 and sm80 now.

Thanks for the information.

I also reproduce this issue on A10G (sm86) with Ubuntu 22.04 and CUDA 12.3.2:
```
(gdb) run --in-shapes 1_3_128_128 --use-cuda --onnx-model RealESRGANv2-animevideo-xsx2.onnx
Starting program: /home/ubuntu/ppl.nn/build/tools/pplnn --in-shapes 1_3_128_128 --use-cuda --onnx-model RealESRGANv2-animevideo-xsx2.onnx
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
ppl.nn version: [0.0.0], commit: [218c8b008e63a446a05c55261d875a7cd0197943]
[New Thread 0x7fffcf1ff000 (LWP 13350)]
[New Thread 0x7fffcd783000 (LWP 13373)]
[INFO][2024-02-05 04:06:26.797][pplnn.cc:318] ***** register CudaEngine *****
[INFO][2024-02-05 04:06:26.800][utils.cc:380] total partition(s) of graph[torch-jit-export]: 1.
[INFO][2024-02-05 04:06:26.801][opt_graph.cc:315] added 94 new bridge kernels
[INFO][2024-02-05 04:06:26.870][algo_conv_hmma.cc:141] Compiling Conv_0
[INFO][2024-02-05 04:06:35.256][algo_conv_hmma.cc:146] select kernel nvIdxnSm80Fp16Conv_hmma16816_nhwc_b64x64_w32x32_k16_s16
[INFO][2024-02-05 04:06:35.326][algo_conv_hmma.cc:141] Compiling Conv_2

Thread 1 "pplnn" received signal SIGFPE, Arithmetic exception.
0x00005555558d9f21 in GetOccupancyScore (cta_size_in_thd=<optimized out>, cta_size_in_warp=16, sm_num=80, cta_num=64, regs_per_cta=64512, smem_per_cta=<optimized out>, max_ctas_per_sm=16, max_thds_per_sm=1536, max_regs_per_sm=65536, max_smem_per_sm=102400, cta_launch_times=@0x7fffffffc7cc: inf) at /home/ubuntu/ppl.nn/deps/ppl.kernel.cuda/src/nn/conv/conv_jit.cc:619
619         int tail_cta_num = cta_num % cta_num_per_launch;
(gdb) print cta_num_per_launch 
$1 = 0
(gdb) bt
#0  0x00005555558d9f21 in GetOccupancyScore (cta_size_in_thd=<optimized out>, cta_size_in_warp=16, sm_num=80, cta_num=64, regs_per_cta=64512, smem_per_cta=<optimized out>, max_ctas_per_sm=16, 
    max_thds_per_sm=1536, max_regs_per_sm=65536, max_smem_per_sm=102400, cta_launch_times=@0x7fffffffc7cc: inf) at /home/ubuntu/ppl.nn/deps/ppl.kernel.cuda/src/nn/conv/conv_jit.cc:619
#1  0x0000555555792bc2 in GetFp16ConvKernelNominees (device_prop=..., type=<optimized out>, conv_param=..., knames=..., params=..., sources=..., spk_only=false)
    at /home/ubuntu/ppl.nn/deps/ppl.kernel.cuda/src/nn/conv/conv_fp16.cu:1205
#2  0x0000555555793719 in PPLCUDAConvolutionJitSelectKernel (device_prop=..., stream=<optimized out>, type=<optimized out>, d_input=<optimized out>, d_flt=<optimized out>, d_output=<optimized out>, 
    bias=0x302212000, d_temp_buf=<optimized out>, algo_param=..., conv_param=..., fuse_param=..., workspace=8589934592) at /home/ubuntu/ppl.nn/deps/ppl.kernel.cuda/src/nn/conv/conv_fp16.cu:1365
#3  0x000055555569d30e in ppl::nn::cuda::TuringHMMAImpgemm::ExcuteTimer (this=0x5555566f8ef0 <ppl::nn::cuda::AlgoFilterManager::Instance()::mgr+3696>, node=<optimized out>, options=...)
    at /home/ubuntu/ppl.nn/src/ppl/nn/engines/cuda/optimizer/algos/algo_conv_hmma.cc:142
#4  0x000055555567e603 in ppl::nn::cuda::AlgoGraph::UpdateNode (this=this@entry=0x7fffffffd1a0, node=node@entry=0x5555579fdc60, options=...)
    at /home/ubuntu/ppl.nn/src/ppl/nn/engines/cuda/optimizer/algos/algo_graph.cc:150
#5  0x000055555563f845 in ppl::nn::cuda::OptGraph::SelectAlgos (this=0x7fffffffd3b0, resource=..., device=<optimized out>) at /home/ubuntu/ppl.nn/src/ppl/nn/engines/cuda/optimizer/opt_graph.cc:476
#6  0x000055555564136e in ppl::nn::cuda::OptGraph::DoOptimize (this=this@entry=0x7fffffffd3b0, resource=..., dev=0x5555569fa100)
    at /home/ubuntu/ppl.nn/src/ppl/nn/engines/cuda/optimizer/opt_graph.cc:626
#7  0x00005555555d86ad in ppl::nn::cuda::CudaEngine::DoOptimize (this=0x5555569f9e40, resource=..., graph=0x7fffffffd6c0, info=0x7fffffffd750) at /usr/include/c++/11/bits/unique_ptr.h:173
#8  0x00005555555db80c in ppl::nn::cuda::CudaEngine::ProcessGraph (this=0x5555569f9e40, resource=..., graph=0x7fffffffd6c0, info=0x7fffffffd750)
    at /home/ubuntu/ppl.nn/src/ppl/nn/engines/cuda/engine.cc:197
#9  0x000055555595e9ab in ppl::nn::utils::GenPartitionsInfoAndShapes (partitions=..., resource=..., graph=<optimized out>, shapes=<optimized out>, par_list=<optimized out>)
    at /home/ubuntu/ppl.nn/src/ppl/nn/optimizers/utils.cc:244
#10 0x0000555555961a09 in ppl::nn::utils::ProcessGraph (resource=..., graph=graph@entry=0x555556be9dc8, info=<optimized out>) at /home/ubuntu/ppl.nn/src/ppl/nn/optimizers/utils.cc:403
#11 0x00005555558fe6a7 in ppl::nn::onnx::RuntimeBuilderImpl::Preprocess (this=0x555556be9d60) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#12 0x00005555555aafe5 in main (argc=<optimized out>, argv=<optimized out>) at /home/ubuntu/ppl.nn/tools/pplnn.cc:1232
```

**Comment by WolframRhodium** [comment]
> Open-Sourced PPL only supports sm75 and sm80 now.

Thanks!
